_extends: simple-masonry-layout:.github/release-drafter.yml
name-template: "sml-v$RESOLVED_VERSION"
tag-template: "sml-v$RESOLVED_VERSION"
tag-prefix: sml-v
include-paths:
  - "packages/simple-masonry-layout/"
