import { useRouter } from "next/router";
import { ImageResponseItem } from "../../api/images";
import { TransitionTarget } from "../../_app";
import Image from "next/image";
import useSWR, { Fetcher } from "swr";

const fetcher: Fetcher<ImageResponseItem, string> = (url) =>
  fetch(url).then((res) => res.json());

export default function ReactExample() {
  const router = useRouter();
  const { id } = router.query;

  const { data: image } = useSWR<ImageResponseItem>(
    `/api/images/${id}`,
    fetcher
  );

  return (
    <div>
      {image && id && (
        <TransitionTarget identifier={`/reactExample/detail/${id}`}>
          <Image
            src={image?.url}
            style={{
              position: "absolute",
              top: 0,
              right: 0,
              bottom: 0,
              left: 0,
              display: "block",
              margin: "auto",
              maxWidth: "calc(100% - 400px)",
            }}
            alt="an image generated by Stable Diffusion"
            width={image.size.width}
            height={image.size.height}
            priority={true}
          />
        </TransitionTarget>
      )}
    </div>
  );
}
