name: "Pull Request Labeler"
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

jobs:
  cron-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Cron Labeler
        uses: fjeremic/cron-labeler@0.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
