name: Publish Simple Masonry Layout React to npmjs
on:
  release:
    types: [published]
    tags:
      - smlr-v[0-9]+.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      - run: npm publish --workspace packages/simple-masonry-layout-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
